import * as User from './User'
import * as Ticket from './Ticket'
import * as Sector from './Sector'
import * as Service from './Service'
import * as Zone from './Zone'
import * as Place from './Place'
import * as Car from './Car'
import * as Body from './Body'
import * as Brand from './Brand'
import * as Model from './Model'
import * as Transmission from './Transmission'
import * as Dcard from './Dcard'
import * as Autoteca from './Autoteca'
import * as Reserve from './Reserve'
import * as History from './History'
import * as Necessitate from './Necessitate'
import * as Favorite from './Favorite'
import * as Ignition from './Ignition'
import * as Accumulator from './Accumulator'
import * as Status from './Status'

export { User, Ticket, Sector, Service, Zone, Place, Car, Body, Brand, Model, Transmission, Dcard, Autoteca, Reserve, History, Necessitate, Favorite, Ignition, Accumulator, Status }
